### INSTRUCTIONS ###
## The purpose of this docker container is to simplify bringing up Gaps while developing.
# 1. Build Gaps Jar
#     - mvn clean install
# 2. Verify Gaps version is correct in "docker-compose-dev.yaml"
#     - update "gapsVersion: 0.8.6" with the correct version
# 3. Bring up development container in background. This will build a docker image if it does not already exist.
#     - docker-compose -f docker-compose-dev.yaml up -d
#
## To test any new changes do the following
#     - build new jars
#     - restart docker container

version: "3"
services:
  gaps:
    container_name: gaps_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8484:8484
    restart: unless-stopped
    expose:
      - "32400"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./GapsWeb/target:/usr/app:ro
