#Copyright 2019 Jason H House
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

gaps:
  #######################################
  #
  #Can read from a folder, Plex, or both
  #At least, one of the two property groups needs to be filled in though
  #
  #######################################

  #List of folders where movies can be pulled from
  folder:
    #Required
    searchFromFolder: true

    #Required if searching from folders
    #List of folders to search in
    folders:
      - /Users/jhouse/Movies

    #Required if searching from folders
    #If the subfolder should be searched in
    recursive: true

    #Required if searching from folders
    #Add any movie formats as needed
    movieFormats:
      - avi
      - mkv
      - mp4
      - mov
      - webm
      - vob
      - flv
      - mts
      - m2ts
      - m4p
      - m4v
      - 3gp
      - 3g2

    #Movie Regex
    #Expected format is Movie Name (Year)
    #Example: The Fast and the Furious (2001)
    yearRegex: \(([1-2][0-9][0-9][0-9])\)

  #Adjust logging as you see fit
logging:
  level:
    root: INFO

# Maximum time the response should be cached (in seconds)
# The cache must re-validate stale resources with the server. Any expired resources must not be used without re-validating.
# The resources are public and any cache may store the response.
spring:
  mvc:
    async:
      request-timeout: -1
  resources:
    cache:
      cachecontrol:
        max-age: 120
        must-revalidate: true
        cache-public: true

# Enable response compression
# The comma-separated list of mime types that should be compressed
# Compress the response only if the response size is at least 1KB
# Enable HTTP/2 support, if the current environment supports it
server:
  port: 8484
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/gaps.p12
    key-store-password: gapsgapsgaps
    key-alias: gaps
security:
  require-ssl: true