name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run minify-input-css
      - run: npm run uglifyjs-index-js
      - run: npm run uglifyjs-configuration-js
      - run: npm run uglifyjs-libraries-js
      - run: npm run uglifyjs-recommended-js
      - run: npm run uglifyjs-common-js
      - run: npm run uglifyjs-payload-js
      - run: npm run uglifyjs-mislabeled-js